### ISSUE TITLE
No link to data file?

### ISSUE THREAD

**Issue by catpat8000** [bellingcat/EDGAR#1]
In the README I see: "I've built a table containing most income statement, balance sheet, and cash flow statement data for every company traded publicly in the U.S. This table is updated periodically, and available here for download as a .CSV file. "

I cannot find a link for this .CSV file?

**Comment by GeorgeDyer** [comment]
Hi, I am facing issues in automatically updating the file, as well as hosting it on github because it is quite large. For now, you can find it here: https://edgar.marketinference.com/
