### ISSUE TITLE
Replace sys.exit with exceptions and handling

### ISSUE THREAD

**Issue by GalenReich** [bellingcat/EDGAR#17]
At the moment, handling the first page of results not loading is done by calling `sys.exit(1)`

I think it would be better to raise and handle a specific exception than call sys.exit(1); if someone used the text_search class they might not expect a call to sys.exit

https://github.com/bellingcat/EDGAR/blob/685865b65ce4f9e3522250060f455e97903e706b/src/text_search.py#L478-L480

https://github.com/bellingcat/EDGAR/blob/685865b65ce4f9e3522250060f455e97903e706b/src/text_search.py#L486-L489

**Comment by NauelSerraino** [comment]
Hi @GalenReich I would be happy to work on it :)

**Comment by GalenReich** [comment]
Hero! I've assigned it to you now!
