### ISSUE TITLE
Union Type is added in Python 3.10

### ISSUE THREAD

**Issue by andy-seleya** [bellingcat/EDGAR#32]
Considering union type is available starting from python 3.10 [(docs)](https://docs.python.org/3/library/stdtypes.html#types-union), adding location based search  #28  will limit python version to 3.10+.

<img width="564" alt="image" src="https://github.com/bellingcat/EDGAR/assets/124227155/bcd76e63-dc7d-4835-ac72-82d8dcdf45bc">

**Comment by GalenReich** [comment]
Or we could add:

```python
from __future__ import annotations
```

**Comment by andy-seleya** [comment]
agree, they should work
